name: build

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9.]+

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Musl
        run: |
          apt-get update
          apt-get install -y musl-tools

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          sed -i -E "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml

      - name: Build (release, musl)
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/memwatch memwatch-linux-x86_64
          strip -s memwatch-linux-x86_64 || true
          sha256sum memwatch-linux-x86_64 > memwatch-linux-x86_64.sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            memwatch-linux-x86_64
            memwatch-linux-x86_64.sha256
